### ISSUE TITLE
File not supported?

### ISSUE THREAD

**Issue by InfiniteAlly1122** [evanugarte/snapchat-memories-downloader#24]
I used the website to download some of my memories. When I tried to view one it said the file is not supported. Any idea on how to fix this and how to view it?

**Comment by cal-overflow** [comment]
@InfiniteAlly1122 
This is likely caused by Snapchat changing the media types from `PHOTO` and `VIDEO` to `Image` and `Video` recently.
I just recently fixed this on my own website (which is quite similar to this one). View it at [downloadmysnapchatmemories.com](http://www.downloadmysnapchatmemories.com).

**Comment by evanugarte** [comment]
Thank u both for the info, @ChristianLisle I really like your website! I'll update the download handler for the website later today to account for the field name change.

**Comment by evanugarte** [comment]
Can confirm the website is working again.
